### PR TITLE
Groupby.nunique

### PR DESCRIPTION
**Pull request by RainFung**
add parameter to check if all columns to be agged

### CODE REVIEW

File: databricks/koalas/groupby.py [hunk 1]
```diff
@@ -602,6 +602,48 @@ def rename_output(pdf):
...
+
+        >>> df.groupby('id').nunique() # doctest: +NORMALIZE_WHITESPACE
+              id  value1  value2
+        id
+        egg    1       1       1
+        ham    1       1       2
+        spam   1       2       1
+        """
+        if not dropna:
+            raise ValueError('nunique do not support `drop=False` now')
```
Comment (HyukjinKwon) [inline databricks/koalas/groupby.py]: Do you mean `dropna`?

File: databricks/koalas/groupby.py [hunk 2]
```diff
@@ -602,6 +602,48 @@ def rename_output(pdf):
...
+        if not self._have_agg_columns:
+            self._agg_columns = self._groupkeys + self._agg_columns
+        return self._reduce_for_stat_function(F.countDistinct, only_numeric=False)
```
Comment (HyukjinKwon) [inline databricks/koalas/groupby.py]: There's `DataFrame.nunique` implementation. Can we follow and ideally deduplicate the logic?

File: databricks/koalas/groupby.py [hunk 3]
```diff
@@ -602,6 +602,48 @@ def rename_output(pdf):
...
+        >>> df.groupby('id').nunique() # doctest: +NORMALIZE_WHITESPACE
+              id  value1  value2
+        id
+        egg    1       1       1
+        ham    1       1       2
+        spam   1       2       1
+        """
+        if not dropna:
+            raise ValueError('nunique do not support `drop=False` now')
+        if not self._have_agg_columns:
```
Comment (HyukjinKwon) [inline databricks/koalas/groupby.py]: Seems like we won't need `_have_agg_columns` but we can simply check, with `isinstance`,  if `self` is `SeriesGroupBy` or `DataFrameGroupBy`.

File: databricks/koalas/groupby.py (hunk 2 above)
Comment (RainFung) [reply databricks/koalas/groupby.py]: Can you give me some more specific code?

File: databricks/koalas/groupby.py [hunk 4]
```diff
@@ -675,6 +675,48 @@ def rename_output(pdf):
...
+        >>> df
+             id  value1 value2
+        0  spam       1      a
+        1   egg       5      b
+        2   egg       5      b
+        3  spam       2      a
+        4   ham       5      x
+        5   ham       5      y
+
+        >>> df.groupby('id').nunique() # doctest: +NORMALIZE_WHITESPACE
```
Comment (HyukjinKwon) [inline databricks/koalas/groupby.py]: Can you add one example that uses Series? for instance, `df.value1.groupby('id').nunique()`

File: databricks/koalas/groupby.py (hunk 2 above)
Comment (HyukjinKwon) [reply databricks/koalas/groupby.py]: You can make a private method called, for instance, `_ nunique` at `DataFrame`.

```python
def _nunique(c, dropna=True):
    count_fn = partial(F.approx_count_distinct, rsd=rsd) if approx else F.countDistinct
    if dropna:
        return count_fn(c).alias(c)
    else:
        return count_fn(c) + F.when(F.count(F.when(self._internal.scol_for(c).isNull(), 1)
                                                  .otherwise(None))
                                          >= 1, 1).otherwise(0))
```

and reuse this here and `DataFrame. nunique`

File: databricks/koalas/groupby.py [hunk 5]
```diff
@@ -675,6 +675,48 @@ def rename_output(pdf):
...
+        -------
+        nunique : DataFrame
+
+        Examples
+        --------
+
+        >>> df = ks.DataFrame({'id': ['spam', 'egg', 'egg', 'spam',
+        ...                           'ham', 'ham'],
+        ...                    'value1': [1, 5, 5, 2, 5, 5],
+        ...                    'value2': list('abbaxy')})
```
Comment (ueshin) [inline databricks/koalas/groupby.py]: nit: `columns=[...]`?

File: databricks/koalas/groupby.py (hunk 2 above)
Comment (RainFung) [reply databricks/koalas/groupby.py]:
```python
    def _nunique(self, col, dropna=True, approx=False, rsd=0.05):
        count_fn = partial(F.approx_count_distinct, rsd=rsd) if approx else F.countDistinct
        if dropna:
            return count_fn(col).alias(col)
        else:
            return (count_fn(col) +
                    F.when(F.count(F.when(self._internal.scol_for(col).isNull(), 1)
                                   .otherwise(None)) >= 1, 1).otherwise(0)).alias(col)
```
Excuse me, i add the `_nunique` function in `DataFrame`.But i want to use it in `groupby`  by using `_reduce_for_stat_function`. It raise errors `_nunique() missing 1 required positional argument: 'col'`.
How can i send `col` to `_nunique`? 
```
        def nunique(self, dropna=True):
        if isinstance(self, DataFrameGroupBy):
            self._agg_columns = self._groupkeys + self._agg_columns
        return self._reduce_for_stat_function(self._kdf._nunique, only_numeric=False)
```

Comment (HyukjinKwon) [reply databricks/koalas/groupby.py]: Okay, let me maybe try it later. Ignore this comment for now.

**Comment by HyukjinKwon** [comment]
@RainFung, can you resolve the conflicts? looks close to go.

**Comment by HyukjinKwon** [comment]
Argh, this conflict was caused by merging #622. Can you update please?

File: databricks/koalas/groupby.py (hunk 2 above)
Comment (RainFung) [reply databricks/koalas/groupby.py]: emmm........ Can you cc this?

**Comment by HyukjinKwon** [comment]
@RainFung, I will merge this one as soon as the tests pass

**Comment by RainFung** [comment]
> @RainFung, I will merge this one as soon as the tests pass

Can you solve this before merge?https://github.com/databricks/koalas/pull/617#discussion_r313191528

File: databricks/koalas/groupby.py [hunk 6]
```diff
@@ -1087,6 +1087,53 @@ def rename_output(pdf):
...
+        >>> df.groupby('id')['value1'].nunique() # doctest: +NORMALIZE_WHITESPACE
+        id
+        egg     1
+        ham     1
+        spam    2
+        Name: value1, dtype: int64
+        """
+        if isinstance(self, DataFrameGroupBy):
+            self._agg_columns = self._groupkeys + self._agg_columns
+        return self._reduce_for_stat_function(self._kdf._nunique(dropna=dropna), only_numeric=False)
```
Comment (HyukjinKwon) [inline databricks/koalas/groupby.py]: Ah, let's just do it in a way you did before.
Ignore my comment https://github.com/databricks/koalas/pull/617#discussion_r310086281 here.

Comment (HyukjinKwon) [reply databricks/koalas/groupby.py]: Sorry for back and forth.

**Comment by RainFung** [comment]
wait to be code reviewed.
