### PR TITLE
Implement DataFrame.mode

### PR DESCRIPTION
**Pull request by xinrong-databricks**
Implement DataFrame.mode:

> Get the mode(s) of each element along the selected axis. The mode of a set of values is the value that appears most often. It can be multiple values.

```
        >>> kdf = ks.DataFrame(
        ...     [("bird", 2, 2), ("mammal", 4, np.nan), ("arthropod", 8, 0), ("bird", 2, np.nan)],
        ...     index=("falcon", "horse", "spider", "ostrich"),
        ...     columns=("species", "legs", "wings"),
        ... )

        >>> kdf
                   species  legs  wings
        falcon        bird     2    2.0
        horse       mammal     4    NaN
        spider   arthropod     8    0.0
        ostrich       bird     2    NaN

        >>> kdf.mode()
          species  legs  wings
        0    bird   2.0    0.0
        1    None   NaN    2.0

        >>> kdf.mode(dropna=False)
          species  legs wings
        0    bird     2  None

        >>> kdf.mode(numeric_only=True)
           legs  wings
        0   2.0    0.0
        1   NaN    2.0
```

### CODE REVIEW

File: databricks/koalas/frame.py [hunk 1]
```diff
@@ -3225,6 +3225,58 @@ def mask(self, cond, other=np.nan) -> "DataFrame":
...
+
+        See Also
+        --------
+        Series.mode : Return the highest frequency value in a Series.
+        Series.value_counts : Return the counts of values in a Series.
+        """
+        axis = validate_axis(axis)
+        assert axis == 0
+
+        def mode(kser, dropna):
```
Comment (xinrong-databricks) [inline databricks/koalas/frame.py:3264]: It fails in CI jobs because of `TypeError: ("mode() got an unexpected keyword argument 'dropna'", 'occurred at index a')`. However, it runs well locally. May I ask if you know the reason by any chance? @ueshin

File: databricks/koalas/frame.py [hunk 2]
```diff
@@ -3225,6 +3225,86 @@ def mask(self, cond, other=np.nan) -> "DataFrame":
...
+        ostrich       bird     2    NaN
+
+        >>> kdf.mode()
+          species  legs  wings
+        0    bird   2.0    0.0
+        1    None   NaN    2.0
+
+        >>> kdf.mode(dropna=False)
+          species  legs wings
+        0    bird     2  None
```
Comment (xinrong-databricks) [inline databricks/koalas/frame.py:3282]: Github CI jobs with Spark 3.0.1 seem to expect 
```
      species  legs  wings
    0    bird     2    NaN
```

Do we know the reason by any chance?

Comment (ueshin) [reply databricks/koalas/frame.py:3282]: The Spark 3.0 behavior seems reasonable.
The difference is caused by https://github.com/apache/spark/commit/8e9bfea1070052ebdd20f4a19b53534533bed909

Comment (ueshin) [reply databricks/koalas/frame.py:3282]: FYI: #2004

Comment (xinrong-databricks) [reply databricks/koalas/frame.py:3282]: Thank you for the fix! Let me update this.

File: databricks/koalas/frame.py [hunk 3]
```diff
@@ -3225,6 +3225,86 @@ def mask(self, cond, other=np.nan) -> "DataFrame":
...
+        """
+        axis = validate_axis(axis)
+        assert axis == 0
+
+        def mode(kser, dropna):
+            return kser.mode(dropna=dropna)
+
+        data = self if not numeric_only else self._get_numeric_data()
+
+        return data.apply(mode, dropna=dropna)
```
[the remark this answers is not in the document]
Comment (xinrong-databricks) [reply databricks/koalas/frame.py]: Makes sense! Let me modify this.

File: databricks/koalas/frame.py [hunk 4]
```diff
@@ -3225,6 +3225,86 @@ def mask(self, cond, other=np.nan) -> "DataFrame":
...
+        >>> kdf.mode(numeric_only=True)
+           legs  wings
+        0   2.0    0.0
+        1   NaN    2.0
+        """
+        axis = validate_axis(axis)
+        assert axis == 0
+
+        def mode(kser, dropna):
+            return kser.mode(dropna=dropna)
```
[the remark this answers is not in the document]
Comment (xinrong-databricks) [reply databricks/koalas/frame.py]: I see. 

I believe `mode` would expect a pandas Series and output a pandas Series. If we annotate the return type of this udf, would it be `ks.Series` or `pd.Series`?

[the remark this answers is not in the document]
Comment (ueshin) [reply databricks/koalas/frame.py]: We should use `ks.Series` or `ks.DataFrame`. https://koalas.readthedocs.io/en/latest/user_guide/typehints.html#koalas-dataframe-and-pandas-dataframe

File: databricks/koalas/frame.py [hunk 5]
```diff
@@ -3225,6 +3225,105 @@ def mask(self, cond, other=np.nan) -> "DataFrame":
...
+            return sdf_most_value.withColumn(
+                new_scol, F.row_number().over(Window.orderBy(F.monotonically_increasing_id()))
+            )
+
+        new_sdf = None
+        for data_scol_name in data._internal.data_spark_column_names:
+            if new_sdf is None:
+                new_sdf = scol_mode(data_scol_name)
+            else:
+                new_sdf = new_sdf.join(scol_mode(data_scol_name), on=[new_scol], how="outer")
```
Comment (ueshin) [inline databricks/koalas/frame.py:3314]: I'm afraid there are so many joins as the number of columns. We want to avoid such cases.
I guess this is a similar case to what we did for `idxmax`/`idxmin`. https://github.com/databricks/koalas/pull/1054#discussion_r352971248

Comment (ueshin) [reply databricks/koalas/frame.py:3314]: Hm, I can't find a good condition to reduce the amount of data so far..

File: databricks/koalas/frame.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (xinrong-databricks) [reply databricks/koalas/frame.py]: The linked guide is helpful, thanks!

File: databricks/koalas/frame.py (hunk 5 above)
Comment (xinrong-databricks) [reply databricks/koalas/frame.py:3314]: Yeah, I see what you mean. In my current implementation, `scol_mode` will generate a new Spark frame per `data_scol_name`, and we combine these Spark frames along the way.

Would it be acceptable with a warning in the docstring showing this operations is expensive?
